### ISSUE TITLE
Warn of unused code not in diff

### ISSUE THREAD

**Issue by neilsardesai** [manicmaniac/danger-periphery#188]
Hello, 

Thanks for making this plugin! It’s pretty great. One feature request:

A lot of times code that was previously used can become unused later, such as after a large refactor. This code might not be part of the git diff. Periphery can identify this type of unused code, but this plugin explicitly filters those results out:

![Screenshot 2024-02-12 at 3 26 34 PM](https://github.com/manicmaniac/danger-periphery/assets/4098825/b53296d6-b97a-4ea8-9f3a-4e4b77d4e97e)

Would it be possible to have an option for not filtering out code that’s not in the diff, and instead logging all Periphery warnings?

**Comment by manicmaniac** [comment]
@neilsardesai Thank you for using danger-periphery.

The option to prevent filtering diff sounds convenient.
I will add a flag or option to disable filtering like `lintAllFiles` in danger-swiftlint
https://github.com/ashfurrow/danger-swiftlint?tab=readme-ov-file#lint-all-files

**Comment by neilsardesai** [comment]
Thank you! That sounds perfect

**Comment by manicmaniac** [comment]
Just published in [v0.3.0](https://github.com/manicmaniac/danger-periphery/releases/tag/v0.3.0) :rocket:

**Comment by neilsardesai** [comment]
Thank you!
