### ISSUE TITLE
Possibility to set error instead of warning

### ISSUE THREAD

**Issue by aiKrice** [manicmaniac/danger-periphery#198]
First of all, awesome plugin, one of the most important one, should be a builtin in a danger iOS setup, thank you for that.

I didnt see any option (hidden ?) to set danger as error instead warning in PR message. It would be nice something such as:

periphery.warning_as_error = true (default = false)
WDYT ?

**Comment by manicmaniac** [comment]
Thank you for using this plugin.

> periphery.warning_as_error = true (default = false)

It sounds great. I would like to implement this idea :+1:

**Comment by manicmaniac** [comment]
Just published 0.3.1 that includes this feature :rocket:

https://github.com/manicmaniac/danger-periphery/releases/tag/v0.3.1

**Comment by aiKrice** [comment]
Thank you very much mate !!!!
