### ISSUE TITLE
Call periphery.scan with augments

### ISSUE THREAD

**Issue by aiKrice** [manicmaniac/danger-periphery#231]
It seems that we can pass argument like we could in command line `--` 
Do you confirm and if yes what is the proper syntax please @manicmaniac

**Comment by manicmaniac** [comment]
@aiKrice 

It converts method's arguments into command-line arguments here.

https://github.com/manicmaniac/danger-periphery/blob/933547119491ef2ec8f766a3356bc2c9a04f9d92/lib/periphery/runner.rb#L22-L39

The rule is simple.

- Remove leading hyphens (`--`)
- Substitute `_` to `-`
- If the option takes an argument, put it as value of Hash
- If the option takes multiple arguments, surround it with an Array
- If the option does not take arguments, just put `true`

Thus, for example,

- `--schemes Foo,Bar` would be `schemes: ["Foo", "Bar"]`
- `--retain-objc-accessible` would be `retain_objc_accessible: true`

**Comment by aiKrice** [comment]
Thank you mate for your reactivity ❤️

**Comment by Xopoko** [comment]
Hello @aiKrice!
How can I pass the -destination argument to xcodebuild when running periphery scan?

I’m trying to use periphery scan within a CI pipeline, and I need to specify the -destination argument for xcodebuild (e.g., -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max'). How can I achieve this when using the Danger plugin for Periphery?

Thanks for your help!

**Comment by manicmaniac** [comment]
Ah, sorry I missed that. Arguments after double-hyphens `--` are currently not supported.

**Comment by manicmaniac** [comment]
I will add this feature by adding options like `build_args`.

**Comment by Xopoko** [comment]
Thanks a lot @manicmaniac!

**Comment by manicmaniac** [comment]
Thank you @Xopoko, the feature has been shipped in 0.4.0 :rocket:
